### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by RP5406** [jasonxtn/Argus#17]
I followed the steps to install argus. When I run python argus.py I receive an error:

File "/home/red/argus/argus.py", line 15, in <module>
from utils.report_generator import generate_report
ModuleNotFoundError: No module named 'utils.report_generator'

**Comment by nevermore23274** [comment]
So I made a quick Dockerfile simply for testing:

```dockerfile
FROM kalilinux/kali-rolling
RUN apt-get update && \
    apt-get install -y python3 python3-pip git
WORKDIR /app
RUN git clone https://github.com/jasonxtn/argus.git /app/argus
WORKDIR /app/argus
RUN pip3 install --break-system-packages -r requirements.txt
CMD ["bash"]
```

You can see there's [a PR here](https://github.com/jasonxtn/Argus/pull/8) that aims to make this a bit more standard, but I tossed this one together simply to try to feel out your issue. The tool runs fine and also seems to not be having any issues beyond me needing to use `python3` in the run command instead of just `python`. (easily fixed, but not really the issue here)

My first guess would be that `report_generator.py` is for some reason not in the utils folder. Have you checked? You may also wish to try to update your python pathing with something like `export PYTHONPATH=$(pwd)` and report back if either of those helped. (given the nature of the tool and your `/home/red` directory, I assume you're on Kali by default)

**Comment by RP5406** [comment]
Yes, I am using Kali and report_generator.py is in utils dir.

**Comment by RP5406** [comment]
you can close this if you want. I don't have time to trouble shoot this. I just wanted to run it and test it.

**Comment by nevermore23274** [comment]
I'm not the maintainer, so I can't close anything. But, you can always try the container route if you're just wanting to try it out. Other than that, good luck.

**Comment by jasonxtn** [comment]
The tool is working fine! Since you’ve confirmed utils.py is in place, try those: 

- Clone the latest version of the project.
- Run it from the terminal ( do not double click or whatever) 
- Check your Python environment
- PYTHONPATH: If the error persists, you can add the project directory to your PYTHONPATH:
export PYTHONPATH=$PYTHONPATH:/path/to/argus
- Try using python3 argus.py

**Comment by RP5406** [comment]
I tried all that, its whatever. You can close this out.

**Comment by RP5406** [comment]
I don't know what the differences are but I got it working on my other Kali VM.
